#!/bin/bash

# This file is part of BPFS. BPFS is copyright 2009-2010 The Regents of the
# University of California. It is distributed under the terms of version 2
# of the GNU GPL. See the file LICENSE for details.

# Run bpfs inside Pin to verify that file system operations are atomic

DIR="`dirname "$0"`"

PIN=$DIR/pin/pin

PINOPTS=${PINOPTS:-}
TOOLOPTS=${TOOLOPTS:-}

if [ ! -d $DIR/pin ]; then
	echo "Pin not found at $DIR/pin/." 1>&2
	echo "Pin is available from http://www.pintool.org/." 1>&2
	echo "bpfsatomic was developed against Pin 27887 gcc4 ia32/intel64." 1>&2
	exit 1
fi

if [ ! -x $PIN ]; then
	echo "Could not find $PIN" 1>&2
	exit 1
fi

# Assume there is just one obj-* so that we don't have to detect the
# appropriate directory
TOOL="`ls $DIR/obj-*/bpfsatomic.so`"

if [ ! -f "$TOOL" ]; then
	echo "Could not find $DIR/obj-*/bpfsatomic.so." 1>&2
	echo "Did you compile bpfsatomic.so? 'make -f makefile-bpfsatomic'." 1>&2
	exit 1
fi

exec $PIN $PINOPTS -t $TOOL $TOOLOPTS -- $DIR/../bpfs $@
